apiVersion: v1
kind: Pod
metadata:
  name: www-vol
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: nginx
  volumes:
    - name: nginx
      persistentVolumeClaim:
        claimName: nginx
